export default [
  {
    id: 1,
    iso2: "BD",
    iso3: "BGD",
    name: "Bangladesh",
    continent: "AS",
    calling_code: "880",
    currency: "BDT",
  },
  {
    id: 2,
    iso2: "BE",
    iso3: "BEL",
    name: "Belgium",
    continent: "EU",
    calling_code: "32",
    currency: "EUR",
  },
  {
    id: 3,
    iso2: "BF",
    iso3: "BFA",
    name: "Burkina Faso",
    continent: "AF",
    calling_code: "226",
    currency: "XOF",
  },
  {
    id: 4,
    iso2: "BG",
    iso3: "BGR",
    name: "Bulgaria",
    continent: "EU",
    calling_code: "359",
    currency: "BGN",
  },
  {
    id: 5,
    iso2: "BA",
    iso3: "BIH",
    name: "Bosnia and Herzegovina",
    continent: "EU",
    calling_code: "387",
    currency: "BAM",
  },
  {
    id: 6,
    iso2: "BB",
    iso3: "BRB",
    name: "Barbados",
    continent: "NA",
    calling_code: "+1-246",
    currency: "BBD",
  },
  {
    id: 7,
    iso2: "WF",
    iso3: "WLF",
    name: "Wallis and Futuna",
    continent: "OC",
    calling_code: "681",
    currency: "XPF",
  },
  {
    id: 8,
    iso2: "BL",
    iso3: "BLM",
    name: "Saint Barthelemy",
    continent: "NA",
    calling_code: "590",
    currency: "EUR",
  },
  {
    id: 9,
    iso2: "BM",
    iso3: "BMU",
    name: "Bermuda",
    continent: "NA",
    calling_code: "+1-441",
    currency: "BMD",
  },
  {
    id: 10,
    iso2: "BN",
    iso3: "BRN",
    name: "Brunei",
    continent: "AS",
    calling_code: "673",
    currency: "BND",
  },
  {
    id: 11,
    iso2: "BO",
    iso3: "BOL",
    name: "Bolivia",
    continent: "SA",
    calling_code: "591",
    currency: "BOB",
  },
  {
    id: 12,
    iso2: "BH",
    iso3: "BHR",
    name: "Bahrain",
    continent: "AS",
    calling_code: "973",
    currency: "BHD",
  },
  {
    id: 13,
    iso2: "BI",
    iso3: "BDI",
    name: "Burundi",
    continent: "AF",
    calling_code: "257",
    currency: "BIF",
  },
  {
    id: 14,
    iso2: "BJ",
    iso3: "BEN",
    name: "Benin",
    continent: "AF",
    calling_code: "229",
    currency: "XOF",
  },
  {
    id: 15,
    iso2: "BT",
    iso3: "BTN",
    name: "Bhutan",
    continent: "AS",
    calling_code: "975",
    currency: "BTN",
  },
  {
    id: 16,
    iso2: "JM",
    iso3: "JAM",
    name: "Jamaica",
    continent: "NA",
    calling_code: "+1-876",
    currency: "JMD",
  },
  {
    id: 18,
    iso2: "BW",
    iso3: "BWA",
    name: "Botswana",
    continent: "AF",
    calling_code: "267",
    currency: "BWP",
  },
  {
    id: 19,
    iso2: "WS",
    iso3: "WSM",
    name: "Samoa",
    continent: "OC",
    calling_code: "685",
    currency: "WST",
  },
  {
    id: 20,
    iso2: "BQ",
    iso3: "BES",
    name: "Bonaire, Saint Eustatius and Saba ",
    continent: "NA",
    calling_code: "599",
    currency: "USD",
  },
  {
    id: 21,
    iso2: "BR",
    iso3: "BRA",
    name: "Brazil",
    continent: "SA",
    calling_code: "55",
    currency: "BRL",
  },
  {
    id: 22,
    iso2: "BS",
    iso3: "BHS",
    name: "Bahamas",
    continent: "NA",
    calling_code: "+1-242",
    currency: "BSD",
  },
  {
    id: 23,
    iso2: "JE",
    iso3: "JEY",
    name: "Jersey",
    continent: "EU",
    calling_code: "+44-1534",
    currency: "GBP",
  },
  {
    id: 24,
    iso2: "BY",
    iso3: "BLR",
    name: "Belarus",
    continent: "EU",
    calling_code: "375",
    currency: "BYR",
  },
  {
    id: 25,
    iso2: "BZ",
    iso3: "BLZ",
    name: "Belize",
    continent: "NA",
    calling_code: "501",
    currency: "BZD",
  },
  {
    id: 26,
    iso2: "RU",
    iso3: "RUS",
    name: "Russia",
    continent: "EU",
    calling_code: "7",
    currency: "RUB",
  },
  {
    id: 27,
    iso2: "RW",
    iso3: "RWA",
    name: "Rwanda",
    continent: "AF",
    calling_code: "250",
    currency: "RWF",
  },
  {
    id: 28,
    iso2: "RS",
    iso3: "SRB",
    name: "Serbia",
    continent: "EU",
    calling_code: "381",
    currency: "RSD",
  },
  {
    id: 29,
    iso2: "TL",
    iso3: "TLS",
    name: "East Timor",
    continent: "OC",
    calling_code: "670",
    currency: "USD",
  },
  {
    id: 30,
    iso2: "RE",
    iso3: "REU",
    name: "Reunion",
    continent: "AF",
    calling_code: "262",
    currency: "EUR",
  },
  {
    id: 31,
    iso2: "TM",
    iso3: "TKM",
    name: "Turkmenistan",
    continent: "AS",
    calling_code: "993",
    currency: "TMT",
  },
  {
    id: 32,
    iso2: "TJ",
    iso3: "TJK",
    name: "Tajikistan",
    continent: "AS",
    calling_code: "992",
    currency: "TJS",
  },
  {
    id: 33,
    iso2: "RO",
    iso3: "ROU",
    name: "Romania",
    continent: "EU",
    calling_code: "40",
    currency: "RON",
  },
  {
    id: 34,
    iso2: "TK",
    iso3: "TKL",
    name: "Tokelau",
    continent: "OC",
    calling_code: "690",
    currency: "NZD",
  },
  {
    id: 35,
    iso2: "GW",
    iso3: "GNB",
    name: "Guinea-Bissau",
    continent: "AF",
    calling_code: "245",
    currency: "XOF",
  },
  {
    id: 36,
    iso2: "GU",
    iso3: "GUM",
    name: "Guam",
    continent: "OC",
    calling_code: "+1-671",
    currency: "USD",
  },
  {
    id: 37,
    iso2: "GT",
    iso3: "GTM",
    name: "Guatemala",
    continent: "NA",
    calling_code: "502",
    currency: "GTQ",
  },
  {
    id: 39,
    iso2: "GR",
    iso3: "GRC",
    name: "Greece",
    continent: "EU",
    calling_code: "30",
    currency: "EUR",
  },
  {
    id: 40,
    iso2: "GQ",
    iso3: "GNQ",
    name: "Equatorial Guinea",
    continent: "AF",
    calling_code: "240",
    currency: "XAF",
  },
  {
    id: 41,
    iso2: "GP",
    iso3: "GLP",
    name: "Guadeloupe",
    continent: "NA",
    calling_code: "590",
    currency: "EUR",
  },
  {
    id: 42,
    iso2: "JP",
    iso3: "JPN",
    name: "Japan",
    continent: "AS",
    calling_code: "81",
    currency: "JPY",
  },
  {
    id: 43,
    iso2: "GY",
    iso3: "GUY",
    name: "Guyana",
    continent: "SA",
    calling_code: "592",
    currency: "GYD",
  },
  {
    id: 44,
    iso2: "GG",
    iso3: "GGY",
    name: "Guernsey",
    continent: "EU",
    calling_code: "+44-1481",
    currency: "GBP",
  },
  {
    id: 45,
    iso2: "GF",
    iso3: "GUF",
    name: "French Guiana",
    continent: "SA",
    calling_code: "594",
    currency: "EUR",
  },
  {
    id: 46,
    iso2: "GE",
    iso3: "GEO",
    name: "Georgia",
    continent: "AS",
    calling_code: "995",
    currency: "GEL",
  },
  {
    id: 47,
    iso2: "GD",
    iso3: "GRD",
    name: "Grenada",
    continent: "NA",
    calling_code: "+1-473",
    currency: "XCD",
  },
  {
    id: 48,
    iso2: "GB",
    iso3: "GBR",
    name: "United Kingdom",
    continent: "EU",
    calling_code: "44",
    currency: "GBP",
  },
  {
    id: 49,
    iso2: "GA",
    iso3: "GAB",
    name: "Gabon",
    continent: "AF",
    calling_code: "241",
    currency: "XAF",
  },
  {
    id: 50,
    iso2: "SV",
    iso3: "SLV",
    name: "El Salvador",
    continent: "NA",
    calling_code: "503",
    currency: "USD",
  },
  {
    id: 51,
    iso2: "GN",
    iso3: "GIN",
    name: "Guinea",
    continent: "AF",
    calling_code: "224",
    currency: "GNF",
  },
  {
    id: 52,
    iso2: "GM",
    iso3: "GMB",
    name: "Gambia",
    continent: "AF",
    calling_code: "220",
    currency: "GMD",
  },
  {
    id: 53,
    iso2: "GL",
    iso3: "GRL",
    name: "Greenland",
    continent: "NA",
    calling_code: "299",
    currency: "DKK",
  },
  {
    id: 54,
    iso2: "GI",
    iso3: "GIB",
    name: "Gibraltar",
    continent: "EU",
    calling_code: "350",
    currency: "GIP",
  },
  {
    id: 55,
    iso2: "GH",
    iso3: "GHA",
    name: "Ghana",
    continent: "AF",
    calling_code: "233",
    currency: "GHS",
  },
  {
    id: 56,
    iso2: "OM",
    iso3: "OMN",
    name: "Oman",
    continent: "AS",
    calling_code: "968",
    currency: "OMR",
  },
  {
    id: 57,
    iso2: "TN",
    iso3: "TUN",
    name: "Tunisia",
    continent: "AF",
    calling_code: "216",
    currency: "TND",
  },
  {
    id: 58,
    iso2: "JO",
    iso3: "JOR",
    name: "Jordan",
    continent: "AS",
    calling_code: "962",
    currency: "JOD",
  },
  {
    id: 59,
    iso2: "HR",
    iso3: "HRV",
    name: "Croatia",
    continent: "EU",
    calling_code: "385",
    currency: "HRK",
  },
  {
    id: 60,
    iso2: "HT",
    iso3: "HTI",
    name: "Haiti",
    continent: "NA",
    calling_code: "509",
    currency: "HTG",
  },
  {
    id: 61,
    iso2: "HU",
    iso3: "HUN",
    name: "Hungary",
    continent: "EU",
    calling_code: "36",
    currency: "HUF",
  },
  {
    id: 62,
    iso2: "HK",
    iso3: "HKG",
    name: "Hong Kong",
    continent: "AS",
    calling_code: "852",
    currency: "HKD",
  },
  {
    id: 63,
    iso2: "HN",
    iso3: "HND",
    name: "Honduras",
    continent: "NA",
    calling_code: "504",
    currency: "HNL",
  },
  {
    id: 64,
    iso2: "HM",
    iso3: "HMD",
    name: "Heard Island and McDonald Islands",
    continent: "AN",
    calling_code: " ",
    currency: "AUD",
  },
  {
    id: 65,
    iso2: "VE",
    iso3: "VEN",
    name: "Venezuela",
    continent: "SA",
    calling_code: "58",
    currency: "VEF",
  },
  {
    id: 66,
    iso2: "PR",
    iso3: "PRI",
    name: "Puerto Rico",
    continent: "NA",
    calling_code: "+1-787 and 1-939",
    currency: "USD",
  },
  {
    id: 67,
    iso2: "PS",
    iso3: "PSE",
    name: "Palestinian Territory",
    continent: "AS",
    calling_code: "970",
    currency: "ILS",
  },
  {
    id: 68,
    iso2: "PW",
    iso3: "PLW",
    name: "Palau",
    continent: "OC",
    calling_code: "680",
    currency: "USD",
  },
  {
    id: 69,
    iso2: "PT",
    iso3: "PRT",
    name: "Portugal",
    continent: "EU",
    calling_code: "351",
    currency: "EUR",
  },
  {
    id: 70,
    iso2: "SJ",
    iso3: "SJM",
    name: "Svalbard and Jan Mayen",
    continent: "EU",
    calling_code: "47",
    currency: "NOK",
  },
  {
    id: 71,
    iso2: "PY",
    iso3: "PRY",
    name: "Paraguay",
    continent: "SA",
    calling_code: "595",
    currency: "PYG",
  },
  {
    id: 72,
    iso2: "IQ",
    iso3: "IRQ",
    name: "Iraq",
    continent: "AS",
    calling_code: "964",
    currency: "IQD",
  },
  {
    id: 73,
    iso2: "PA",
    iso3: "PAN",
    name: "Panama",
    continent: "NA",
    calling_code: "507",
    currency: "PAB",
  },
  {
    id: 74,
    iso2: "PF",
    iso3: "PYF",
    name: "French Polynesia",
    continent: "OC",
    calling_code: "689",
    currency: "XPF",
  },
  {
    id: 75,
    iso2: "PG",
    iso3: "PNG",
    name: "Papua New Guinea",
    continent: "OC",
    calling_code: "675",
    currency: "PGK",
  },
  {
    id: 76,
    iso2: "PE",
    iso3: "PER",
    name: "Peru",
    continent: "SA",
    calling_code: "51",
    currency: "PEN",
  },
  {
    id: 77,
    iso2: "PK",
    iso3: "PAK",
    name: "Pakistan",
    continent: "AS",
    calling_code: "92",
    currency: "PKR",
  },
  {
    id: 78,
    iso2: "PH",
    iso3: "PHL",
    name: "Philippines",
    continent: "AS",
    calling_code: "63",
    currency: "PHP",
  },
  {
    id: 79,
    iso2: "PN",
    iso3: "PCN",
    name: "Pitcairn",
    continent: "OC",
    calling_code: "870",
    currency: "NZD",
  },
  {
    id: 80,
    iso2: "PL",
    iso3: "POL",
    name: "Poland",
    continent: "EU",
    calling_code: "48",
    currency: "PLN",
  },
  {
    id: 81,
    iso2: "PM",
    iso3: "SPM",
    name: "Saint Pierre and Miquelon",
    continent: "NA",
    calling_code: "508",
    currency: "EUR",
  },
  {
    id: 82,
    iso2: "ZM",
    iso3: "ZMB",
    name: "Zambia",
    continent: "AF",
    calling_code: "260",
    currency: "ZMK",
  },
  {
    id: 83,
    iso2: "EH",
    iso3: "ESH",
    name: "Western Sahara",
    continent: "AF",
    calling_code: "212",
    currency: "MAD",
  },
  {
    id: 84,
    iso2: "EE",
    iso3: "EST",
    name: "Estonia",
    continent: "EU",
    calling_code: "372",
    currency: "EUR",
  },
  {
    id: 85,
    iso2: "EG",
    iso3: "EGY",
    name: "Egypt",
    continent: "AF",
    calling_code: "20",
    currency: "EGP",
  },
  {
    id: 86,
    iso2: "ZA",
    iso3: "ZAF",
    name: "South Africa",
    continent: "AF",
    calling_code: "27",
    currency: "ZAR",
  },
  {
    id: 87,
    iso2: "EC",
    iso3: "ECU",
    name: "Ecuador",
    continent: "SA",
    calling_code: "593",
    currency: "USD",
  },
  {
    id: 88,
    iso2: "IT",
    iso3: "ITA",
    name: "Italy",
    continent: "EU",
    calling_code: "39",
    currency: "EUR",
  },
  {
    id: 89,
    iso2: "VN",
    iso3: "VNM",
    name: "Vietnam",
    continent: "AS",
    calling_code: "84",
    currency: "VND",
  },
  {
    id: 90,
    iso2: "SB",
    iso3: "SLB",
    name: "Solomon Islands",
    continent: "OC",
    calling_code: "677",
    currency: "SBD",
  },
  {
    id: 91,
    iso2: "ET",
    iso3: "ETH",
    name: "Ethiopia",
    continent: "AF",
    calling_code: "251",
    currency: "ETB",
  },
  {
    id: 92,
    iso2: "SO",
    iso3: "SOM",
    name: "Somalia",
    continent: "AF",
    calling_code: "252",
    currency: "SOS",
  },
  {
    id: 93,
    iso2: "ZW",
    iso3: "ZWE",
    name: "Zimbabwe",
    continent: "AF",
    calling_code: "263",
    currency: "ZWL",
  },
  {
    id: 94,
    iso2: "SA",
    iso3: "SAU",
    name: "Saudi Arabia",
    continent: "AS",
    calling_code: "966",
    currency: "SAR",
  },
  {
    id: 95,
    iso2: "ES",
    iso3: "ESP",
    name: "Spain",
    continent: "EU",
    calling_code: "34",
    currency: "EUR",
  },
  {
    id: 96,
    iso2: "ER",
    iso3: "ERI",
    name: "Eritrea",
    continent: "AF",
    calling_code: "291",
    currency: "ERN",
  },
  {
    id: 97,
    iso2: "ME",
    iso3: "MNE",
    name: "Montenegro",
    continent: "EU",
    calling_code: "382",
    currency: "EUR",
  },
  {
    id: 98,
    iso2: "MD",
    iso3: "MDA",
    name: "Moldova",
    continent: "EU",
    calling_code: "373",
    currency: "MDL",
  },
  {
    id: 99,
    iso2: "MG",
    iso3: "MDG",
    name: "Madagascar",
    continent: "AF",
    calling_code: "261",
    currency: "MGA",
  },
  {
    id: 100,
    iso2: "MF",
    iso3: "MAF",
    name: "Saint Martin",
    continent: "NA",
    calling_code: "590",
    currency: "EUR",
  },
  {
    id: 101,
    iso2: "MA",
    iso3: "MAR",
    name: "Morocco",
    continent: "AF",
    calling_code: "212",
    currency: "MAD",
  },
  {
    id: 102,
    iso2: "MC",
    iso3: "MCO",
    name: "Monaco",
    continent: "EU",
    calling_code: "377",
    currency: "EUR",
  },
  {
    id: 103,
    iso2: "UZ",
    iso3: "UZB",
    name: "Uzbekistan",
    continent: "AS",
    calling_code: "998",
    currency: "UZS",
  },
  {
    id: 104,
    iso2: "MM",
    iso3: "MMR",
    name: "Myanmar",
    continent: "AS",
    calling_code: "95",
    currency: "MMK",
  },
  {
    id: 105,
    iso2: "ML",
    iso3: "MLI",
    name: "Mali",
    continent: "AF",
    calling_code: "223",
    currency: "XOF",
  },
  {
    id: 106,
    iso2: "MO",
    iso3: "MAC",
    name: "Macao",
    continent: "AS",
    calling_code: "853",
    currency: "MOP",
  },
  {
    id: 107,
    iso2: "MN",
    iso3: "MNG",
    name: "Mongolia",
    continent: "AS",
    calling_code: "976",
    currency: "MNT",
  },
  {
    id: 108,
    iso2: "MH",
    iso3: "MHL",
    name: "Marshall Islands",
    continent: "OC",
    calling_code: "692",
    currency: "USD",
  },
  {
    id: 109,
    iso2: "MK",
    iso3: "MKD",
    name: "Macedonia",
    continent: "EU",
    calling_code: "389",
    currency: "MKD",
  },
  {
    id: 110,
    iso2: "MU",
    iso3: "MUS",
    name: "Mauritius",
    continent: "AF",
    calling_code: "230",
    currency: "MUR",
  },
  {
    id: 111,
    iso2: "MT",
    iso3: "MLT",
    name: "Malta",
    continent: "EU",
    calling_code: "356",
    currency: "EUR",
  },
  {
    id: 112,
    iso2: "MW",
    iso3: "MWI",
    name: "Malawi",
    continent: "AF",
    calling_code: "265",
    currency: "MWK",
  },
  {
    id: 113,
    iso2: "MV",
    iso3: "MDV",
    name: "Maldives",
    continent: "AS",
    calling_code: "960",
    currency: "MVR",
  },
  {
    id: 114,
    iso2: "MQ",
    iso3: "MTQ",
    name: "Martinique",
    continent: "NA",
    calling_code: "596",
    currency: "EUR",
  },
  {
    id: 115,
    iso2: "MP",
    iso3: "MNP",
    name: "Northern Mariana Islands",
    continent: "OC",
    calling_code: "+1-670",
    currency: "USD",
  },
  {
    id: 116,
    iso2: "MS",
    iso3: "MSR",
    name: "Montserrat",
    continent: "NA",
    calling_code: "+1-664",
    currency: "XCD",
  },
  {
    id: 117,
    iso2: "MR",
    iso3: "MRT",
    name: "Mauritania",
    continent: "AF",
    calling_code: "222",
    currency: "MRO",
  },
  {
    id: 118,
    iso2: "IM",
    iso3: "IMN",
    name: "Isle of Man",
    continent: "EU",
    calling_code: "+44-1624",
    currency: "GBP",
  },
  {
    id: 119,
    iso2: "UG",
    iso3: "UGA",
    name: "Uganda",
    continent: "AF",
    calling_code: "256",
    currency: "UGX",
  },
  {
    id: 120,
    iso2: "TZ",
    iso3: "TZA",
    name: "Tanzania",
    continent: "AF",
    calling_code: "255",
    currency: "TZS",
  },
  {
    id: 121,
    iso2: "MY",
    iso3: "MYS",
    name: "Malaysia",
    continent: "AS",
    calling_code: "60",
    currency: "MYR",
  },
  {
    id: 122,
    iso2: "MX",
    iso3: "MEX",
    name: "Mexico",
    continent: "NA",
    calling_code: "52",
    currency: "MXN",
  },
  {
    id: 123,
    iso2: "IL",
    iso3: "ISR",
    name: "Israel",
    continent: "AS",
    calling_code: "972",
    currency: "ILS",
  },
  {
    id: 124,
    iso2: "FR",
    iso3: "FRA",
    name: "France",
    continent: "EU",
    calling_code: "33",
    currency: "EUR",
  },
  {
    id: 125,
    iso2: "IO",
    iso3: "IOT",
    name: "British Indian Ocean Territory",
    continent: "AS",
    calling_code: "246",
    currency: "USD",
  },
  {
    id: 126,
    iso2: "SH",
    iso3: "SHN",
    name: "Saint Helena",
    continent: "AF",
    calling_code: "290",
    currency: "SHP",
  },
  {
    id: 127,
    iso2: "FI",
    iso3: "FIN",
    name: "Finland",
    continent: "EU",
    calling_code: "358",
    currency: "EUR",
  },
  {
    id: 128,
    iso2: "FJ",
    iso3: "FJI",
    name: "Fiji",
    continent: "OC",
    calling_code: "679",
    currency: "FJD",
  },
  {
    id: 129,
    iso2: "FK",
    iso3: "FLK",
    name: "Falkland Islands",
    continent: "SA",
    calling_code: "500",
    currency: "FKP",
  },
  {
    id: 130,
    iso2: "FM",
    iso3: "FSM",
    name: "Micronesia",
    continent: "OC",
    calling_code: "691",
    currency: "USD",
  },
  {
    id: 131,
    iso2: "FO",
    iso3: "FRO",
    name: "Faroe Islands",
    continent: "EU",
    calling_code: "298",
    currency: "DKK",
  },
  {
    id: 132,
    iso2: "NI",
    iso3: "NIC",
    name: "Nicaragua",
    continent: "NA",
    calling_code: "505",
    currency: "NIO",
  },
  {
    id: 133,
    iso2: "NL",
    iso3: "NLD",
    name: "Netherlands",
    continent: "EU",
    calling_code: "31",
    currency: "EUR",
  },
  {
    id: 134,
    iso2: "NO",
    iso3: "NOR",
    name: "Norway",
    continent: "EU",
    calling_code: "47",
    currency: "NOK",
  },
  {
    id: 135,
    iso2: "NA",
    iso3: "NAM",
    name: "Namibia",
    continent: "AF",
    calling_code: "264",
    currency: "NAD",
  },
  {
    id: 136,
    iso2: "VU",
    iso3: "VUT",
    name: "Vanuatu",
    continent: "OC",
    calling_code: "678",
    currency: "VUV",
  },
  {
    id: 137,
    iso2: "NC",
    iso3: "NCL",
    name: "New Caledonia",
    continent: "OC",
    calling_code: "687",
    currency: "XPF",
  },
  {
    id: 138,
    iso2: "NE",
    iso3: "NER",
    name: "Niger",
    continent: "AF",
    calling_code: "227",
    currency: "XOF",
  },
  {
    id: 139,
    iso2: "NF",
    iso3: "NFK",
    name: "Norfolk Island",
    continent: "OC",
    calling_code: "672",
    currency: "AUD",
  },
  {
    id: 140,
    iso2: "NG",
    iso3: "NGA",
    name: "Nigeria",
    continent: "AF",
    calling_code: "234",
    currency: "NGN",
  },
  {
    id: 141,
    iso2: "NZ",
    iso3: "NZL",
    name: "New Zealand",
    continent: "OC",
    calling_code: "64",
    currency: "NZD",
  },
  {
    id: 142,
    iso2: "NP",
    iso3: "NPL",
    name: "Nepal",
    continent: "AS",
    calling_code: "977",
    currency: "NPR",
  },
  {
    id: 143,
    iso2: "NR",
    iso3: "NRU",
    name: "Nauru",
    continent: "OC",
    calling_code: "674",
    currency: "AUD",
  },
  {
    id: 144,
    iso2: "NU",
    iso3: "NIU",
    name: "Niue",
    continent: "OC",
    calling_code: "683",
    currency: "NZD",
  },
  {
    id: 145,
    iso2: "CK",
    iso3: "COK",
    name: "Cook Islands",
    continent: "OC",
    calling_code: "682",
    currency: "NZD",
  },
  {
    id: 147,
    iso2: "CI",
    iso3: "CIV",
    name: "Ivory Coast",
    continent: "AF",
    calling_code: "225",
    currency: "XOF",
  },
  {
    id: 148,
    iso2: "CH",
    iso3: "CHE",
    name: "Switzerland",
    continent: "EU",
    calling_code: "41",
    currency: "CHF",
  },
  {
    id: 149,
    iso2: "CO",
    iso3: "COL",
    name: "Colombia",
    continent: "SA",
    calling_code: "57",
    currency: "COP",
  },
  {
    id: 150,
    iso2: "CN",
    iso3: "CHN",
    name: "China",
    continent: "AS",
    calling_code: "86",
    currency: "CNY",
  },
  {
    id: 151,
    iso2: "CM",
    iso3: "CMR",
    name: "Cameroon",
    continent: "AF",
    calling_code: "237",
    currency: "XAF",
  },
  {
    id: 152,
    iso2: "CL",
    iso3: "CHL",
    name: "Chile",
    continent: "SA",
    calling_code: "56",
    currency: "CLP",
  },
  {
    id: 153,
    iso2: "CC",
    iso3: "CCK",
    name: "Cocos Islands",
    continent: "AS",
    calling_code: "61",
    currency: "AUD",
  },
  {
    id: 154,
    iso2: "CA",
    iso3: "CAN",
    name: "Canada",
    continent: "NA",
    calling_code: "1",
    currency: "CAD",
  },
  {
    id: 155,
    iso2: "CG",
    iso3: "COG",
    name: "Republic of the Congo",
    continent: "AF",
    calling_code: "242",
    currency: "XAF",
  },
  {
    id: 156,
    iso2: "CF",
    iso3: "CAF",
    name: "Central African Republic",
    continent: "AF",
    calling_code: "236",
    currency: "XAF",
  },
  {
    id: 157,
    iso2: "CD",
    iso3: "COD",
    name: "Democratic Republic of the Congo",
    continent: "AF",
    calling_code: "243",
    currency: "CDF",
  },
  {
    id: 158,
    iso2: "CZ",
    iso3: "CZE",
    name: "Czech Republic",
    continent: "EU",
    calling_code: "420",
    currency: "CZK",
  },
  {
    id: 159,
    iso2: "CY",
    iso3: "CYP",
    name: "Cyprus",
    continent: "EU",
    calling_code: "357",
    currency: "EUR",
  },
  {
    id: 160,
    iso2: "CX",
    iso3: "CXR",
    name: "Christmas Island",
    continent: "AS",
    calling_code: "61",
    currency: "AUD",
  },
  {
    id: 161,
    iso2: "CR",
    iso3: "CRI",
    name: "Costa Rica",
    continent: "NA",
    calling_code: "506",
    currency: "CRC",
  },
  {
    id: 162,
    iso2: "CW",
    iso3: "CUW",
    name: "Curacao",
    continent: "NA",
    calling_code: "599",
    currency: "ANG",
  },
  {
    id: 163,
    iso2: "CV",
    iso3: "CPV",
    name: "Cape Verde",
    continent: "AF",
    calling_code: "238",
    currency: "CVE",
  },
  {
    id: 164,
    iso2: "CU",
    iso3: "CUB",
    name: "Cuba",
    continent: "NA",
    calling_code: "53",
    currency: "CUP",
  },
  {
    id: 165,
    iso2: "SZ",
    iso3: "SWZ",
    name: "Swaziland",
    continent: "AF",
    calling_code: "268",
    currency: "SZL",
  },
  {
    id: 166,
    iso2: "SY",
    iso3: "SYR",
    name: "Syria",
    continent: "AS",
    calling_code: "963",
    currency: "SYP",
  },
  {
    id: 167,
    iso2: "SX",
    iso3: "SXM",
    name: "Sint Maarten",
    continent: "NA",
    calling_code: "599",
    currency: "ANG",
  },
  {
    id: 168,
    iso2: "KG",
    iso3: "KGZ",
    name: "Kyrgyzstan",
    continent: "AS",
    calling_code: "996",
    currency: "KGS",
  },
  {
    id: 169,
    iso2: "KE",
    iso3: "KEN",
    name: "Kenya",
    continent: "AF",
    calling_code: "254",
    currency: "KES",
  },
  {
    id: 170,
    iso2: "SS",
    iso3: "SSD",
    name: "South Sudan",
    continent: "AF",
    calling_code: "211",
    currency: "SSP",
  },
  {
    id: 171,
    iso2: "SR",
    iso3: "SUR",
    name: "Suriname",
    continent: "SA",
    calling_code: "597",
    currency: "SRD",
  },
  {
    id: 172,
    iso2: "KI",
    iso3: "KIR",
    name: "Kiribati",
    continent: "OC",
    calling_code: "686",
    currency: "AUD",
  },
  {
    id: 173,
    iso2: "KH",
    iso3: "KHM",
    name: "Cambodia",
    continent: "AS",
    calling_code: "855",
    currency: "KHR",
  },
  {
    id: 174,
    iso2: "KN",
    iso3: "KNA",
    name: "Saint Kitts and Nevis",
    continent: "NA",
    calling_code: "+1-869",
    currency: "XCD",
  },
  {
    id: 175,
    iso2: "KM",
    iso3: "COM",
    name: "Comoros",
    continent: "AF",
    calling_code: "269",
    currency: "KMF",
  },
  {
    id: 176,
    iso2: "ST",
    iso3: "STP",
    name: "Sao Tome and Principe",
    continent: "AF",
    calling_code: "239",
    currency: "STD",
  },
  {
    id: 177,
    iso2: "SK",
    iso3: "SVK",
    name: "Slovakia",
    continent: "EU",
    calling_code: "421",
    currency: "EUR",
  },
  {
    id: 178,
    iso2: "KR",
    iso3: "KOR",
    name: "South Korea",
    continent: "AS",
    calling_code: "82",
    currency: "KRW",
  },
  {
    id: 179,
    iso2: "SI",
    iso3: "SVN",
    name: "Slovenia",
    continent: "EU",
    calling_code: "386",
    currency: "EUR",
  },
  {
    id: 180,
    iso2: "KP",
    iso3: "PRK",
    name: "North Korea",
    continent: "AS",
    calling_code: "850",
    currency: "KPW",
  },
  {
    id: 181,
    iso2: "KW",
    iso3: "KWT",
    name: "Kuwait",
    continent: "AS",
    calling_code: "965",
    currency: "KWD",
  },
  {
    id: 182,
    iso2: "SN",
    iso3: "SEN",
    name: "Senegal",
    continent: "AF",
    calling_code: "221",
    currency: "XOF",
  },
  {
    id: 183,
    iso2: "SM",
    iso3: "SMR",
    name: "San Marino",
    continent: "EU",
    calling_code: "378",
    currency: "EUR",
  },
  {
    id: 184,
    iso2: "SL",
    iso3: "SLE",
    name: "Sierra Leone",
    continent: "AF",
    calling_code: "232",
    currency: "SLL",
  },
  {
    id: 185,
    iso2: "SC",
    iso3: "SYC",
    name: "Seychelles",
    continent: "AF",
    calling_code: "248",
    currency: "SCR",
  },
  {
    id: 186,
    iso2: "KZ",
    iso3: "KAZ",
    name: "Kazakhstan",
    continent: "AS",
    calling_code: "7",
    currency: "KZT",
  },
  {
    id: 187,
    iso2: "KY",
    iso3: "CYM",
    name: "Cayman Islands",
    continent: "NA",
    calling_code: "+1-345",
    currency: "KYD",
  },
  {
    id: 188,
    iso2: "SG",
    iso3: "SGP",
    name: "Singapore",
    continent: "AS",
    calling_code: "65",
    currency: "SGD",
  },
  {
    id: 189,
    iso2: "SE",
    iso3: "SWE",
    name: "Sweden",
    continent: "EU",
    calling_code: "46",
    currency: "SEK",
  },
  {
    id: 190,
    iso2: "SD",
    iso3: "SDN",
    name: "Sudan",
    continent: "AF",
    calling_code: "249",
    currency: "SDG",
  },
  {
    id: 191,
    iso2: "DO",
    iso3: "DOM",
    name: "Dominican Republic",
    continent: "NA",
    calling_code: "+1-809 and 1-829",
    currency: "DOP",
  },
  {
    id: 192,
    iso2: "DM",
    iso3: "DMA",
    name: "Dominica",
    continent: "NA",
    calling_code: "+1-767",
    currency: "XCD",
  },
  {
    id: 193,
    iso2: "DJ",
    iso3: "DJI",
    name: "Djibouti",
    continent: "AF",
    calling_code: "253",
    currency: "DJF",
  },
  {
    id: 194,
    iso2: "DK",
    iso3: "DNK",
    name: "Denmark",
    continent: "EU",
    calling_code: "45",
    currency: "DKK",
  },
  {
    id: 195,
    iso2: "VG",
    iso3: "VGB",
    name: "British Virgin Islands",
    continent: "NA",
    calling_code: "+1-284",
    currency: "USD",
  },
  {
    id: 196,
    iso2: "DE",
    iso3: "DEU",
    name: "Germany",
    continent: "EU",
    calling_code: "49",
    currency: "EUR",
  },
  {
    id: 197,
    iso2: "YE",
    iso3: "YEM",
    name: "Yemen",
    continent: "AS",
    calling_code: "967",
    currency: "YER",
  },
  {
    id: 198,
    iso2: "DZ",
    iso3: "DZA",
    name: "Algeria",
    continent: "AF",
    calling_code: "213",
    currency: "DZD",
  },
  {
    id: 199,
    iso2: "US",
    iso3: "USA",
    name: "United States",
    continent: "NA",
    calling_code: "1",
    currency: "USD",
  },
  {
    id: 200,
    iso2: "UY",
    iso3: "URY",
    name: "Uruguay",
    continent: "SA",
    calling_code: "598",
    currency: "UYU",
  },
  {
    id: 201,
    iso2: "YT",
    iso3: "MYT",
    name: "Mayotte",
    continent: "AF",
    calling_code: "262",
    currency: "EUR",
  },
  {
    id: 202,
    iso2: "UM",
    iso3: "UMI",
    name: "United States Minor Outlying Islands",
    continent: "OC",
    calling_code: "1",
    currency: "USD",
  },
  {
    id: 203,
    iso2: "LB",
    iso3: "LBN",
    name: "Lebanon",
    continent: "AS",
    calling_code: "961",
    currency: "LBP",
  },
  {
    id: 204,
    iso2: "LC",
    iso3: "LCA",
    name: "Saint Lucia",
    continent: "NA",
    calling_code: "+1-758",
    currency: "XCD",
  },
  {
    id: 205,
    iso2: "LA",
    iso3: "LAO",
    name: "Laos",
    continent: "AS",
    calling_code: "856",
    currency: "LAK",
  },
  {
    id: 206,
    iso2: "TV",
    iso3: "TUV",
    name: "Tuvalu",
    continent: "OC",
    calling_code: "688",
    currency: "AUD",
  },
  {
    id: 207,
    iso2: "TW",
    iso3: "TWN",
    name: "Taiwan",
    continent: "AS",
    calling_code: "886",
    currency: "TWD",
  },
  {
    id: 208,
    iso2: "TT",
    iso3: "TTO",
    name: "Trinidad and Tobago",
    continent: "NA",
    calling_code: "+1-868",
    currency: "TTD",
  },
  {
    id: 209,
    iso2: "TR",
    iso3: "TUR",
    name: "Turkey",
    continent: "AS",
    calling_code: "90",
    currency: "TRY",
  },
  {
    id: 210,
    iso2: "LK",
    iso3: "LKA",
    name: "Sri Lanka",
    continent: "AS",
    calling_code: "94",
    currency: "LKR",
  },
  {
    id: 211,
    iso2: "LI",
    iso3: "LIE",
    name: "Liechtenstein",
    continent: "EU",
    calling_code: "423",
    currency: "CHF",
  },
  {
    id: 212,
    iso2: "LV",
    iso3: "LVA",
    name: "Latvia",
    continent: "EU",
    calling_code: "371",
    currency: "EUR",
  },
  {
    id: 213,
    iso2: "TO",
    iso3: "TON",
    name: "Tonga",
    continent: "OC",
    calling_code: "676",
    currency: "TOP",
  },
  {
    id: 214,
    iso2: "LT",
    iso3: "LTU",
    name: "Lithuania",
    continent: "EU",
    calling_code: "370",
    currency: "LTL",
  },
  {
    id: 215,
    iso2: "LU",
    iso3: "LUX",
    name: "Luxembourg",
    continent: "EU",
    calling_code: "352",
    currency: "EUR",
  },
  {
    id: 216,
    iso2: "LR",
    iso3: "LBR",
    name: "Liberia",
    continent: "AF",
    calling_code: "231",
    currency: "LRD",
  },
  {
    id: 217,
    iso2: "LS",
    iso3: "LSO",
    name: "Lesotho",
    continent: "AF",
    calling_code: "266",
    currency: "LSL",
  },
  {
    id: 218,
    iso2: "TH",
    iso3: "THA",
    name: "Thailand",
    continent: "AS",
    calling_code: "66",
    currency: "THB",
  },
  {
    id: 220,
    iso2: "TG",
    iso3: "TGO",
    name: "Togo",
    continent: "AF",
    calling_code: "228",
    currency: "XOF",
  },
  {
    id: 221,
    iso2: "TD",
    iso3: "TCD",
    name: "Chad",
    continent: "AF",
    calling_code: "235",
    currency: "XAF",
  },
  {
    id: 222,
    iso2: "TC",
    iso3: "TCA",
    name: "Turks and Caicos Islands",
    continent: "NA",
    calling_code: "+1-649",
    currency: "USD",
  },
  {
    id: 223,
    iso2: "LY",
    iso3: "LBY",
    name: "Libya",
    continent: "AF",
    calling_code: "218",
    currency: "LYD",
  },
  {
    id: 224,
    iso2: "VA",
    iso3: "VAT",
    name: "Vatican",
    continent: "EU",
    calling_code: "379",
    currency: "EUR",
  },
  {
    id: 225,
    iso2: "VC",
    iso3: "VCT",
    name: "Saint Vincent and the Grenadines",
    continent: "NA",
    calling_code: "+1-784",
    currency: "XCD",
  },
  {
    id: 226,
    iso2: "AE",
    iso3: "ARE",
    name: "United Arab Emirates",
    continent: "AS",
    calling_code: "971",
    currency: "AED",
  },
  {
    id: 227,
    iso2: "AD",
    iso3: "AND",
    name: "Andorra",
    continent: "EU",
    calling_code: "376",
    currency: "EUR",
  },
  {
    id: 228,
    iso2: "AG",
    iso3: "ATG",
    name: "Antigua and Barbuda",
    continent: "NA",
    calling_code: "+1-268",
    currency: "XCD",
  },
  {
    id: 229,
    iso2: "AF",
    iso3: "AFG",
    name: "Afghanistan",
    continent: "AS",
    calling_code: "93",
    currency: "AFN",
  },
  {
    id: 230,
    iso2: "AI",
    iso3: "AIA",
    name: "Anguilla",
    continent: "NA",
    calling_code: "+1-264",
    currency: "XCD",
  },
  {
    id: 231,
    iso2: "VI",
    iso3: "VIR",
    name: "U.S. Virgin Islands",
    continent: "NA",
    calling_code: "+1-340",
    currency: "USD",
  },
  {
    id: 232,
    iso2: "IS",
    iso3: "ISL",
    name: "Iceland",
    continent: "EU",
    calling_code: "354",
    currency: "ISK",
  },
  {
    id: 233,
    iso2: "IR",
    iso3: "IRN",
    name: "Iran",
    continent: "AS",
    calling_code: "98",
    currency: "IRR",
  },
  {
    id: 234,
    iso2: "AM",
    iso3: "ARM",
    name: "Armenia",
    continent: "AS",
    calling_code: "374",
    currency: "AMD",
  },
  {
    id: 235,
    iso2: "AL",
    iso3: "ALB",
    name: "Albania",
    continent: "EU",
    calling_code: "355",
    currency: "ALL",
  },
  {
    id: 236,
    iso2: "AO",
    iso3: "AGO",
    name: "Angola",
    continent: "AF",
    calling_code: "244",
    currency: "AOA",
  },
  {
    id: 238,
    iso2: "AS",
    iso3: "ASM",
    name: "American Samoa",
    continent: "OC",
    calling_code: "+1-684",
    currency: "USD",
  },
  {
    id: 239,
    iso2: "AR",
    iso3: "ARG",
    name: "Argentina",
    continent: "SA",
    calling_code: "54",
    currency: "ARS",
  },
  {
    id: 240,
    iso2: "AU",
    iso3: "AUS",
    name: "Australia",
    continent: "OC",
    calling_code: "61",
    currency: "AUD",
  },
  {
    id: 241,
    iso2: "AT",
    iso3: "AUT",
    name: "Austria",
    continent: "EU",
    calling_code: "43",
    currency: "EUR",
  },
  {
    id: 242,
    iso2: "AW",
    iso3: "ABW",
    name: "Aruba",
    continent: "NA",
    calling_code: "297",
    currency: "AWG",
  },
  {
    id: 243,
    iso2: "IN",
    iso3: "IND",
    name: "India",
    continent: "AS",
    calling_code: "91",
    currency: "INR",
  },
  {
    id: 244,
    iso2: "AX",
    iso3: "ALA",
    name: "Aland Islands",
    continent: "EU",
    calling_code: "+358-18",
    currency: "EUR",
  },
  {
    id: 245,
    iso2: "AZ",
    iso3: "AZE",
    name: "Azerbaijan",
    continent: "AS",
    calling_code: "994",
    currency: "AZN",
  },
  {
    id: 246,
    iso2: "IE",
    iso3: "IRL",
    name: "Ireland",
    continent: "EU",
    calling_code: "353",
    currency: "EUR",
  },
  {
    id: 247,
    iso2: "ID",
    iso3: "IDN",
    name: "Indonesia",
    continent: "AS",
    calling_code: "62",
    currency: "IDR",
  },
  {
    id: 248,
    iso2: "UA",
    iso3: "UKR",
    name: "Ukraine",
    continent: "EU",
    calling_code: "380",
    currency: "UAH",
  },
  {
    id: 249,
    iso2: "QA",
    iso3: "QAT",
    name: "Qatar",
    continent: "AS",
    calling_code: "974",
    currency: "QAR",
  },
  {
    id: 250,
    iso2: "MZ",
    iso3: "MOZ",
    name: "Mozambique",
    continent: "AF",
    calling_code: "258",
    currency: "MZN",
  },
];
