export const IM_MODE_PARTY = 'party';
export const IM_MODE_CHAT = 'chat';
export const IM_TAB_INBOX = 'inbox';
export const IM_TAB_ARCHIVE = 'archive';

export const CONTACT_TYPE_USER = 'user';
export const CONTACT_TYPE_GROUP = 'group';
export const CONTACT_TYPE_FEAT = 'feat';
export const CONTACT_TYPE_SYS = 'sys';

export const GLOBAL_ROOM = 'GLOBAL';
export const FEAT_CONTACT_ID = -1;

export const TEMP_CONTACT_PREFIX = 'TMP';

// Message Type
export const MESSAGE_TYPE_FRIEND_IM = 0;
export const MESSAGE_TYPE_GROUP_IM = 100;
export const MESSAGE_TYPE_GROUP_PM = 200;
export const MESSAGE_TYPE_BROADCAST = 300;
export const MESSAGE_TYPE_LIKED = 400;
export const MESSAGE_TYPE_COMMENT = 500;
export const MESSAGE_TYPE_INVITATION = 600;
export const MESSAGE_TYPE_SYSTEM = 700;
export const MESSAGE_TYPE_FRIEND_APPLY = 800;
export const MESSAGE_TYPE_FRIEND_ACCEPT = 900;
export const MESSAGE_TYPE_FRIEND_REJECT = 1000;
export const MESSAGE_TYPE_FRIEND_RECALL = 2000;

export const MESSAGE_TYPE_DEMAND = 1100;
export const MESSAGE_TYPE_GROUP_MERGE_REQUEST = 1200;
export const MESSAGE_TYPE_GROUP_MERGED = 1300;
export const MESSAGE_TYPE_GROUP_DISMISS = 1400;
export const MESSAGE_TYPE_GROUP_RESTORE = 1500;
export const MESSAGE_TYPE_GROUP_NEW_MEMBER = 1600;
export const MESSAGE_TYPE_GROUP_BLACK = 1700;
export const MESSAGE_TYPE_GROUP_UNBLACK = 1800;
export const MESSAGE_TYPE_GROUP_MEMBER_REMOVE = 1810;
export const MESSAGE_TYPE_GROUP_MEMBER_RESTORE = 1820;
export const MESSAGE_TYPE_GROUP_MERGE_REQUEST_REJECT = 1900;

export const MESSAGE_TYPE_GROUP_NEW = 2100;
export const MESSAGE_TYPE_RELATION_REQUEST = 2200;
export const MESSAGE_TYPE_RELATION_ACCEPT = 2300;
export const MESSAGE_TYPE_RELATION_REJECT = 2400;
export const MESSAGE_TYPE_GROUP_RENAME = 2500;
export const MESSAGE_TYPE_ORDER_ERROR = 2600;
export const MESSAGE_TYPE_RECEIVING_ACCOUNT_MISSING = 2700;

export const MESSAGE_TYPE_GROUP_MERGE_REQUEST_INVALID = -1000;

export const MESSAGE_TYPE_DZ_REWORDING_SUBMIT = 3000;
export const MESSAGE_TYPE_DZ_REWORDING_AUDIT = 3100;
export const MESSAGE_TYPE_DZ_REWORDING_COMMENT = 3200;
export const MESSAGE_TYPE_DZ_REWORDING_LIKE = 3300;
export const MESSAGE_TYPE_DZ_COLLABORATOR_JOIN = 3400;
export const MESSAGE_TYPE_DZ_COLLABORATOR_CHANGE = 3500;

// draft collaborator
export const MESSAGE_COLLABORATOR_OWNER = 0;
export const MESSAGE_COLLABORATOR_ADMIN = 100;
export const MESSAGE_COLLABORATOR_PARTICIPATOR = 200;

//
export const NODE_STRUCTURE_TITLE = 0;
export const NODE_STRUCTURE_SUMMARY = 100;
export const NODE_STRUCTURE_PARAGRAPH = 200;
export const NODE_STRUCTURE_COVER = 300;

export const hashMap = {
  [NODE_STRUCTURE_TITLE]: 'title',
  [NODE_STRUCTURE_SUMMARY]: 'summary',
  [NODE_STRUCTURE_PARAGRAPH]: 'content',
  [NODE_STRUCTURE_COVER]: 'cover',
};
export const structureMap = {
  [NODE_STRUCTURE_TITLE]: 'title',
  [NODE_STRUCTURE_SUMMARY]: 'summary',
  [NODE_STRUCTURE_PARAGRAPH]: 'paragraph',
  [NODE_STRUCTURE_COVER]: 'cover',
};
// commerce related messages
// export const MESSAGE_TYPE_ORDER_RECEIVED = 3000;
// export const MESSAGE_TYPE_ORDER_CANCELED = 3001;
// export const MESSAGE_TYPE_ORDER_ACCEPTED = 3002;
// export const MESSAGE_TYPE_ORDER_REJECTED = 3003;
// export const MESSAGE_TYPE_ORDER_READY_TO_START = 3004;
// export const MESSAGE_TYPE_ORDER_FOR_PROVIDER_TO_CONFIRM_START = 3005;
// export const MESSAGE_TYPE_ORDER_FOR_CONSUMER_TO_CONFIRM_START = 3006;
// export const MESSAGE_TYPE_ORDER_STARTED = 3007;
// export const MESSAGE_TYPE_ORDER_REFUND_REQUESTED = 3008;
// export const MESSAGE_TYPE_ORDER_REFUND_CONFIRMED = 3009;
// export const MESSAGE_TYPE_ORDER_REFUND_REJECTED = 3010;
// export const MESSAGE_TYPE_ORDER_REFUND_HANDLED = 3011;

export const UESR_INBOX_MESSAGE_TYPES = [
  MESSAGE_TYPE_FRIEND_IM,
  MESSAGE_TYPE_BROADCAST,
  MESSAGE_TYPE_FRIEND_APPLY,
  MESSAGE_TYPE_FRIEND_ACCEPT,
  MESSAGE_TYPE_FRIEND_REJECT,
  MESSAGE_TYPE_FRIEND_RECALL,
];

export const USER_ARCHIVE_MESSAGE_TYPES = [
  MESSAGE_TYPE_BROADCAST,
  MESSAGE_TYPE_FRIEND_IM,
  MESSAGE_TYPE_FRIEND_APPLY,
  MESSAGE_TYPE_FRIEND_ACCEPT,
  MESSAGE_TYPE_FRIEND_REJECT,
  MESSAGE_TYPE_COMMENT,
  MESSAGE_TYPE_LIKED,
];

export const GROUP_INBOX_MESSAGE_TPYES = [
  MESSAGE_TYPE_GROUP_IM,
  MESSAGE_TYPE_GROUP_PM,
  MESSAGE_TYPE_BROADCAST,
  MESSAGE_TYPE_GROUP_MERGE_REQUEST,
  MESSAGE_TYPE_GROUP_MERGED,
  MESSAGE_TYPE_GROUP_DISMISS,
  MESSAGE_TYPE_GROUP_RESTORE,
  MESSAGE_TYPE_GROUP_NEW_MEMBER,
  MESSAGE_TYPE_GROUP_BLACK,
  MESSAGE_TYPE_GROUP_UNBLACK,
  MESSAGE_TYPE_GROUP_MERGE_REQUEST_REJECT,
  MESSAGE_TYPE_GROUP_NEW,
  MESSAGE_TYPE_GROUP_RENAME,
  // Dimzou related
  MESSAGE_TYPE_DZ_REWORDING_SUBMIT,
  MESSAGE_TYPE_DZ_REWORDING_AUDIT,
  MESSAGE_TYPE_DZ_REWORDING_COMMENT,
  MESSAGE_TYPE_DZ_REWORDING_LIKE,
  MESSAGE_TYPE_DZ_COLLABORATOR_JOIN,
  MESSAGE_TYPE_DZ_COLLABORATOR_CHANGE,
];

export const GROUP_ARCHIVE_MESSAGE_TYPES = [
  MESSAGE_TYPE_GROUP_PM,
  MESSAGE_TYPE_GROUP_IM,
  MESSAGE_TYPE_GROUP_NEW,
  MESSAGE_TYPE_GROUP_DISMISS,
  MESSAGE_TYPE_GROUP_RESTORE,
  MESSAGE_TYPE_GROUP_NEW_MEMBER,
  MESSAGE_TYPE_GROUP_BLACK,
  MESSAGE_TYPE_GROUP_UNBLACK,
  MESSAGE_TYPE_GROUP_MEMBER_REMOVE,
  MESSAGE_TYPE_GROUP_MEMBER_RESTORE,
  MESSAGE_TYPE_GROUP_MERGE_REQUEST,
  MESSAGE_TYPE_GROUP_MERGE_REQUEST_REJECT,
  MESSAGE_TYPE_BROADCAST,

  MESSAGE_TYPE_GROUP_RENAME,
  // Dimzou related
  MESSAGE_TYPE_DZ_REWORDING_SUBMIT,
  MESSAGE_TYPE_DZ_REWORDING_AUDIT,
  MESSAGE_TYPE_DZ_REWORDING_COMMENT,
  MESSAGE_TYPE_DZ_REWORDING_LIKE,
  MESSAGE_TYPE_DZ_COLLABORATOR_JOIN,
  MESSAGE_TYPE_DZ_COLLABORATOR_CHANGE,
];

export const FEAT_INBOX_MESSAGE_TYPES = [
  MESSAGE_TYPE_BROADCAST,
  MESSAGE_TYPE_FRIEND_APPLY,
  MESSAGE_TYPE_FRIEND_ACCEPT,
  MESSAGE_TYPE_FRIEND_REJECT,
  MESSAGE_TYPE_DEMAND,
  MESSAGE_TYPE_GROUP_MERGE_REQUEST,
  MESSAGE_TYPE_GROUP_MERGED,
  MESSAGE_TYPE_GROUP_DISMISS,
  MESSAGE_TYPE_GROUP_RESTORE,
  // MESSAGE_TYPE_GROUP_NEW_MEMBER,
  MESSAGE_TYPE_GROUP_BLACK,
  MESSAGE_TYPE_GROUP_UNBLACK,
  MESSAGE_TYPE_GROUP_MERGE_REQUEST_REJECT,
  MESSAGE_TYPE_GROUP_NEW,
  MESSAGE_TYPE_GROUP_RENAME,
  MESSAGE_TYPE_ORDER_ERROR,
  MESSAGE_TYPE_RECEIVING_ACCOUNT_MISSING,
];

export const FEAT_ARCHIVE_MESSAGE_TYPES = [
  MESSAGE_TYPE_FRIEND_APPLY,
  MESSAGE_TYPE_GROUP_MERGE_REQUEST,
  MESSAGE_TYPE_GROUP_MERGE_REQUEST_REJECT,
  MESSAGE_TYPE_FRIEND_ACCEPT,
  MESSAGE_TYPE_FRIEND_REJECT,
];

export const GLOBAL_INBOX_MESSAGE_TYPES = [MESSAGE_TYPE_BROADCAST];

// Contact Status
export const CONTACT_LIST_STATUS_STRANGER = 0;
export const CONTACT_LIST_STATUS_CREATING = 100;
export const CONTACT_LIST_STATUS_APPLYING = 200;
export const CONTACT_LIST_STATUS_CREATED = 300;
export const CONTACT_LIST_STATUS_RECALLED = 400;
export const CONTACT_LIST_STATUS_REJECTED = 500;
export const CONTACT_LIST_STATUS_BLACK = 600;

export const GROUP_STATUS_CREATED = 0;
export const GROUP_STATUS_REQUESTING_MERGE = 100;
export const GROUP_STATUS_CHECKING_MERGE = 200;
export const GROUP_STATUS_DISMISS = 300;
export const GROUP_STATUS_DELETED = 500;

// Group Merge Status

export const GROUP_MERGE_REQUEST_STATUS_APPLYING = 0;
export const GROUP_MERGE_REQUEST_STATUS_APPROVED = 100;
export const GROUP_MERGE_REQUEST_STATUS_REJECTED = 200;
export const GROUP_MERGE_REQUEST_STATUS_INVALID = 300;
