export default [
  {
    id: "r16Xhpe4G",
    kind: "article",
    title: "amet sed atque",
    body: "Provident eos voluptatem dolore molestiae consequuntur aut est aut voluptatem. Et aliquid totam commodi eos saepe alias aperiam. Impedit id qui recusandae ut sint. Voluptates rerum odit esse expedita cupiditate accusamus ab ut.\n \rArchitecto debitis magnam. Autem minus alias incidunt facere. Aut animi quod autem aut quia eaque et dolorum. Quisquam magnam debitis.\n \rCum quisquam cumque voluptatem. Nesciunt ullam dolores qui ut eum. Corporis a debitis quam reiciendis omnis voluptatum est tempora. Voluptas unde iusto est praesentium dolor totam. Consequatur nihil voluptas est beatae.",
    cover: "http://lorempixel.com/640/480/fashion",
    author: {
      id: "BkeaQ36eVf",
      username: "Cory_Hand56",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/davecraige/128.jpg",
      location: "West Felipaton",
      localTime: "20:35",
      expertise: "Central Branding Executive",
    },
  },
  {
    id: "H1-TmnTeNM",
    kind: "article",
    title: "vitae dolorem suscipit",
    body: "Maiores nihil quidem velit ipsam. Exercitationem rem in tempore occaecati ratione pariatur repellendus id architecto. Exercitationem nemo dignissimos ad qui recusandae minima tempora.\n \rQuasi nulla et quis. Laborum voluptas rerum ipsum impedit tenetur. Quo eveniet quas quia voluptas est ut hic libero sunt. Rem repudiandae occaecati assumenda et. Officiis et corporis. Aut quo vel consectetur expedita non.\n \rQuis et mollitia eos. Modi occaecati sit tempora odit qui. Minima ex enim culpa perspiciatis. Voluptate beatae ut incidunt quis.",
    cover: "http://lorempixel.com/640/480/nightlife",
    author: {
      id: "ryMTXhaxVG",
      username: "Erik14",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/joshaustin/128.jpg",
      location: "Lake Khalid",
      localTime: "15:58",
      expertise: "Future Optimization Manager",
    },
  },
  {
    id: "H1X67nTx4M",
    kind: "article",
    title: "minus sint dolorem",
    body: "Maxime sunt quod a cum. Amet aliquid voluptas ad aut. Odit occaecati accusantium omnis est exercitationem eos rerum. Quidem recusandae et atque est reiciendis minima esse. Cumque voluptas ea quis.\n \rOfficiis voluptatem voluptatibus voluptate ea dolor voluptate provident. Velit corrupti laudantium assumenda. Voluptates perspiciatis quod vel.\n \rSoluta tempore totam provident cumque ut adipisci. Id ea aut praesentium illum. Alias porro tempora molestiae. Qui porro culpa.",
    cover: "http://lorempixel.com/640/480/city",
    author: {
      id: "SkEp72Te4z",
      username: "Adolf99",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/victorDubugras/128.jpg",
      location: "South Madelyn",
      localTime: "16:25",
      expertise: "National Data Orchestrator",
    },
  },
  {
    id: "SkH6X3axVG",
    kind: "article",
    title: "quae dolores dolore",
    body: "Excepturi et perferendis nesciunt eum est error. Eos eos enim. Voluptatem cumque doloremque hic vitae. Quaerat praesentium nulla quam sint necessitatibus est corrupti. Id autem consectetur repellat ut et qui. Sit aut odit qui.\n \rVeniam dolor voluptas neque voluptate quis nobis id. Veritatis tempora sint ut. Delectus nihil eos incidunt voluptatibus in explicabo et vero possimus.\n \rQuaerat aut qui vitae reprehenderit facere dolores facilis impedit ad. Doloremque consequuntur cum sit. Dolor libero deleniti est voluptate beatae. Maxime ut rerum laboriosam deserunt hic impedit. Rerum veniam veniam rerum. Quia quaerat nihil doloribus sit atque.",
    cover: "http://lorempixel.com/640/480/abstract",
    author: {
      id: "BkITXn6gVM",
      username: "Magdalena.Gorczany",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/hugocornejo/128.jpg",
      location: "New Zechariah",
      localTime: "22:41",
      expertise: "Direct Optimization Agent",
    },
  },
  {
    id: "r1v6QnTxEG",
    kind: "article",
    title: "consectetur sit ipsa",
    body: "Error repellat tenetur quaerat optio et quos. Sunt ipsa modi explicabo molestiae. Sequi earum natus dolores dolorem ut fugiat dolorem omnis.\n \rQuae reprehenderit consectetur voluptatem esse nulla voluptatem est autem voluptatem. Ullam est perspiciatis nihil corrupti asperiores. Quas illo consequatur tempore distinctio. Porro molestiae repellat est mollitia veniam non perspiciatis.\n \rVoluptatem et laborum doloribus. Numquam nam iusto ipsam. Saepe adipisci enim consequatur amet. Dignissimos qui autem eligendi voluptatem.",
    cover: "http://lorempixel.com/640/480/business",
    author: {
      id: "Hkd6X3axNG",
      username: "Janis_Nolan",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/kanickairaj/128.jpg",
      location: "Treutelbury",
      localTime: "12:41",
      expertise: "Human Accountability Analyst",
    },
  },
  {
    id: "SyKpXh6gVM",
    kind: "article",
    title: "laboriosam aut ut",
    body: "Qui vel sapiente. Aut molestiae iusto possimus minus laborum expedita omnis tenetur. Est totam nam iusto ea itaque tempore vel. Accusantium exercitationem tempora rem et. Iure consectetur et dolores magnam nemo veniam est iure.\n \rVoluptatem consectetur ad. Eveniet accusamus unde placeat inventore repellat. Ducimus dolor deserunt dignissimos odit corrupti. Harum quam est et. Rerum eaque ullam. Sit rem quisquam quo perspiciatis quaerat quis consequatur repellendus.\n \rAut ipsam deserunt et unde doloribus voluptatem fugiat libero explicabo. Ratione et ullam laudantium praesentium. Et et consequuntur accusantium vel magnam ducimus. Explicabo ipsam a eum amet cum natus. Illum id dolorem placeat quo et impedit debitis qui iste.",
    cover: "http://lorempixel.com/640/480/people",
    author: {
      id: "Skc6m3peVM",
      username: "Luna.Swaniawski",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/darcystonge/128.jpg",
      location: "Nitzscheville",
      localTime: "22:03",
      expertise: "Internal Paradigm Facilitator",
    },
  },
  {
    id: "SyjT73pgNM",
    kind: "article",
    title: "esse corrupti et",
    body: "Quia eaque architecto accusantium earum vel sint. Commodi totam perspiciatis quo nobis distinctio quo optio sapiente molestiae. Doloribus quia eveniet. Sed amet aliquid sunt est facere unde.\n \rSaepe incidunt tempora ullam voluptas. Minima praesentium voluptatem et et nihil. Sed repellendus neque molestias veniam sit labore quod debitis. Facere consectetur voluptates molestias est illum. Soluta quas repellendus dicta. Dolorum qui enim voluptatem dignissimos quia fugit sit fugit.\n \rAut cupiditate sed. Commodi voluptate odit amet nemo. Cumque nobis asperiores qui quos quae sit ea corrupti natus. Reiciendis ullam commodi quod.",
    cover: "http://lorempixel.com/640/480/abstract",
    author: {
      id: "ryh6Qh6eEG",
      username: "Hosea_Considine",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/devinhalladay/128.jpg",
      location: "East Lewshire",
      localTime: "14:27",
      expertise: "Principal Implementation Specialist",
    },
  },
  {
    id: "rJpamhpx4z",
    kind: "article",
    title: "ullam rerum qui",
    body: "Et dicta voluptas nihil quia. Dolor suscipit tenetur laudantium est optio iure ex hic labore. Quo laboriosam cupiditate quis. Id autem labore.\n \rEt ipsa maiores deleniti dignissimos sed et aut. Soluta quae molestias reiciendis sapiente et delectus nesciunt quis ipsa. Non molestiae non saepe sed praesentium vitae.\n \rAliquid ut vel perferendis nihil accusamus aut. Sunt tempora eos quidem. Qui facere sequi est voluptatem error porro. Deserunt vel voluptatem. Quia totam et ut commodi laudantium earum cupiditate quia dolor. Nisi mollitia est doloribus ducimus vero voluptas praesentium enim dolore.",
    cover: "http://lorempixel.com/640/480/technics",
    author: {
      id: "SkCp72axVM",
      username: "Gaylord.Ferry1",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/isnifer/128.jpg",
      location: "Port Avaside",
      localTime: "04:37",
      expertise: "Forward Mobility Liaison",
    },
  },
  {
    id: "BJkgpQhaeVM",
    kind: "article",
    title: "cupiditate necessitatibus sequi",
    body: "Culpa sit officiis corrupti. Aperiam odio rerum et cumque quae voluptatibus. Veritatis voluptatem nihil deserunt voluptas voluptatem esse dolore tempora. Dolores est omnis. Dolorum dignissimos dolorem voluptatem suscipit rem.\n \rIste omnis aliquam ut qui eligendi. Explicabo sit sapiente aut molestiae voluptatem. Ut quod hic consequuntur sit nostrum. Est in ab. Qui quibusdam ut non mollitia voluptatibus eos distinctio nesciunt.\n \rAlias sequi accusantium et. Numquam accusamus excepturi illum et. Consectetur magni aspernatur aliquam maiores quia earum necessitatibus. Voluptatem quas officiis. Nesciunt odit facilis sed aut architecto eos. Sequi reprehenderit eveniet ad aliquam non et.",
    cover: "http://lorempixel.com/640/480/nightlife",
    author: {
      id: "Hyeg6mhTeVM",
      username: "Karen_OKeefe",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/steynviljoen/128.jpg",
      location: "Marionmouth",
      localTime: "08:50",
      expertise: "Dynamic Markets Strategist",
    },
  },
  {
    id: "BkbeTX2axNf",
    kind: "article",
    title: "expedita eaque praesentium",
    body: "Vel et neque vel magnam est consequatur. Sed ut est quas cum. Qui eius quae facilis voluptas ut. Eligendi hic dignissimos earum consectetur adipisci. Aut est sapiente est voluptatibus ipsa voluptatibus sequi.\n \rDolores nulla quibusdam consequatur est dolorem. Ducimus sequi dolore dicta iure accusamus occaecati harum ullam corporis. Perferendis ab quam quaerat sit non praesentium vel. Vel eius et dicta. Quibusdam eaque ea excepturi repellendus similique rerum optio non.\n \rEveniet sequi et in sapiente aliquam. Quia nesciunt aut est velit praesentium neque soluta blanditiis eveniet. Magnam sed quibusdam ex neque quis vitae et pariatur non. Consectetur placeat inventore tempore explicabo in nostrum et voluptatum.",
    cover: "http://lorempixel.com/640/480/nightlife",
    author: {
      id: "H1GlaXnpeVG",
      username: "Patrick8",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/gregrwilkinson/128.jpg",
      location: "Sheilachester",
      localTime: "21:08",
      expertise: "Legacy Directives Director",
    },
  },
  {
    id: "HJXl6mnax4f",
    kind: "article",
    title: "excepturi cum eligendi",
    body: "Et ea libero fugit. Quam ex provident. Dolorem accusamus quia quos sint. Est qui officiis alias voluptas qui quis sed iusto debitis. Nesciunt qui tenetur. Reprehenderit magni vitae officiis commodi optio vel.\n \rImpedit qui sit quis mollitia ipsam exercitationem ducimus. Et animi quia. Illo voluptas natus sint expedita temporibus accusamus voluptatem odit. Ea corrupti nam dolor est facere sed et. Illo corrupti sunt et. Nihil maiores et omnis eius ea officia nulla est nam.\n \rNisi ea quaerat atque nam non facere. Alias et eos delectus doloribus officiis porro. Vitae quod natus et.",
    cover: "http://lorempixel.com/640/480/transport",
    author: {
      id: "HJEx6Q3axNG",
      username: "Aubree5",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/meln1ks/128.jpg",
      location: "Lake Jaclynton",
      localTime: "17:22",
      expertise: "Internal Research Associate",
    },
  },
  {
    id: "r1Bx6726xEf",
    kind: "article",
    title: "ipsa non eaque",
    body: "Maxime magni harum atque velit quia magnam dignissimos. Et aspernatur consequuntur cupiditate aut ipsa sint. Cumque aut enim vitae. Est sed mollitia qui. Molestias enim ut maiores vel deserunt. Aliquam et dicta aut quibusdam.\n \rPorro et dicta voluptas dolor quis culpa consequuntur. Sunt quia esse eius possimus perferendis quis. Aut et numquam earum. Ut unde exercitationem laudantium sit quidem nisi consectetur ad repellat. Inventore dolor repudiandae enim qui atque voluptatem reiciendis omnis.\n \rDoloremque et laudantium. Nisi consequatur quo sed. Ex necessitatibus itaque et. Totam ratione nemo illo iusto ut neque unde.",
    cover: "http://lorempixel.com/640/480/city",
    author: {
      id: "By8gaXnagEf",
      username: "Rosemary.Reinger",
      avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/alek_djuric/128.jpg",
      location: "Port Joelle",
      localTime: "23:23",
      expertise: "National Factors Supervisor",
    },
  },
];
