export default [
  {
    id: "r1g0ib0bM",
    kind: "comment",
    content: "Nihil totam officiis voluptatem enim dolorem minus similique debitis. Id et voluptate odit nobis ut praesentium et. Autem quam alias corporis aliquam sint dolor soluta veniam. Commodi commodi quae voluptatem consectetur perferendis voluptatem enim numquam.",
    createdAt: "2017-04-11T12:24:17.981Z",
    full_name: "Adah Bashirian",
    expertise: "Human Tactics Coordinator",
    email: "Alessandra4@hotmail.com",
    avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/shoaib253/128.jpg",
    replys: [
      {
        id: "H1aJ2-CbG",
        kind: "comment",
        content: "Vero asperiores quia distinctio magnam animi molestiae nemo aut. Doloribus qui quisquam id. Quia ut ea aperiam dolor id omnis nemo. Vero assumenda ut rerum et eum voluptas laudantium.",
        createdAt: "2017-09-30T04:16:33.914Z",
        full_name: "Ms. Estell Strosin",
        expertise: "Future Creative Strategist",
        email: "Davion_Bechtelar@hotmail.com",
      },
      {
        id: "rJQZhbAZf",
        kind: "comment",
        content: "Ea quod neque eum soluta enim voluptatem magni est tenetur. Et eos rerum ex sunt itaque aut. Suscipit ipsa dolores.",
        createdAt: "2017-12-02T14:13:37.098Z",
        full_name: "Clyde Becker",
        expertise: "Regional Tactics Consultant",
        email: "Abdiel_Greenholt@yahoo.com",
        avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/balakayuriy/128.jpg",
        replys: [
          {
            id: "ByafnWAZz",
            kind: "comment",
            content: "Et et ad aperiam aperiam. Et enim dolorum corrupti. Non et sunt et dolorum pariatur quam. Expedita facere alias qui ut eos illum odio.",
            createdAt: "2017-06-30T13:44:38.239Z",
            full_name: "Adah Bashirian",
            expertise: "Human Tactics Coordinator",
            email: "Alessandra4@hotmail.com",
            avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/shoaib253/128.jpg",
          },
          {
            id: "B1f42ZRZM",
            kind: "comment",
            content: "Laborum mollitia aperiam fugit dolores officiis aut et. Deserunt reiciendis qui ut eum hic eos aperiam quaerat fugiat. Quis assumenda veritatis quasi earum consequatur quae quibusdam aut perferendis. Provident blanditiis odio nostrum eveniet et et sit ut voluptatem. Est quia repellendus et reiciendis cupiditate. Maiores aut quaerat aut sunt excepturi qui qui.",
            createdAt: "2017-08-13T16:55:31.436Z",
            full_name: "Rosina Pagac",
            expertise: "Central Usability Associate",
            email: "Tyrel.Hegmann12@yahoo.com",
          },
        ],
      },
    ],
  }, {
    id: "HyhB2-AZM",
    kind: "comment",
    content: "Nihil cupiditate error est eos aut officiis. Consequatur delectus tempore numquam et necessitatibus. Sint et et ratione ut nemo rerum.",
    createdAt: "2017-06-10T23:33:18.899Z",
    full_name: "Zelda Green",
    expertise: "Human Intranet Representative",
    email: "Victoria.Hilll@yahoo.com",
  }, {
    id: "ry06nW0WG",
    kind: "comment",
    content: "Harum aut cumque odio. Quo velit sit ex recusandae. Quos quas unde. Sed mollitia enim magni quod et accusamus repellat nihil quis. Repellat assumenda et eaque est. Aspernatur deserunt autem iure odit.",
    createdAt: "2017-08-20T22:53:54.691Z",
    full_name: "Brannon Purdy",
    expertise: "Customer Marketing Liaison",
    email: "Donny_Lang5@gmail.com",
    avatar: "https://s3.amazonaws.com/uifaces/faces/twitter/atanism/128.jpg",
  },
];
