export const COMMENTABLE_TYPE_ORDER = 0;
export const COMMENTABLE_TYPE_CAREER = 100;
export const COMMENTABLE_TYPE_EDUCATION = 200;
export const COMMENTABLE_TYPE_EVENT = 300;
export const COMMENTABLE_TYPE_PUBLICATION = 500;

export const CHANNEL_OBJECT_TYPE_MAP = {
  event: COMMENTABLE_TYPE_EVENT,
  publication: COMMENTABLE_TYPE_PUBLICATION,
  education: COMMENTABLE_TYPE_EDUCATION,
  career_experience: COMMENTABLE_TYPE_CAREER,
  order: COMMENTABLE_TYPE_ORDER,
};
