export default [
  { id: 1, iso2: "BD", name: "Bangladesh", callingCode: "880" },
  { id: 2, iso2: "BE", name: "Belgium", callingCode: "32" },
  { id: 3, iso2: "BF", name: "Burkina Faso", callingCode: "226" },
  { id: 4, iso2: "BG", name: "Bulgaria", callingCode: "359" },
  { id: 5, iso2: "BA", name: "Bosnia and Herzegovina", callingCode: "387" },
  { id: 6, iso2: "BB", name: "Barbados", callingCode: "+1-246" },
  { id: 7, iso2: "WF", name: "Wallis and Futuna", callingCode: "681" },
  { id: 8, iso2: "BL", name: "Saint Barthelemy", callingCode: "590" },
  { id: 9, iso2: "BM", name: "Bermuda", callingCode: "+1-441" },
  { id: 10, iso2: "BN", name: "Brunei", callingCode: "673" },
  { id: 11, iso2: "BO", name: "Bolivia", callingCode: "591" },
  { id: 12, iso2: "BH", name: "Bahrain", callingCode: "973" },
  { id: 13, iso2: "BI", name: "Burundi", callingCode: "257" },
  { id: 14, iso2: "BJ", name: "Benin", callingCode: "229" },
  { id: 15, iso2: "BT", name: "Bhutan", callingCode: "975" },
  { id: 16, iso2: "JM", name: "Jamaica", callingCode: "+1-876" },
  { id: 17, iso2: "BV", name: "Bouvet Island", callingCode: "" },
  { id: 18, iso2: "BW", name: "Botswana", callingCode: "267" },
  { id: 19, iso2: "WS", name: "Samoa", callingCode: "685" },
  {
    id: 20,
    iso2: "BQ",
    name: "Bonaire, Saint Eustatius and Saba ",
    callingCode: "599",
  },
  { id: 21, iso2: "BR", name: "Brazil", callingCode: "55" },
  { id: 22, iso2: "BS", name: "Bahamas", callingCode: "+1-242" },
  { id: 23, iso2: "JE", name: "Jersey", callingCode: "+44-1534" },
  { id: 24, iso2: "BY", name: "Belarus", callingCode: "375" },
  { id: 25, iso2: "BZ", name: "Belize", callingCode: "501" },
  { id: 26, iso2: "RU", name: "Russia", callingCode: "7" },
  { id: 27, iso2: "RW", name: "Rwanda", callingCode: "250" },
  { id: 28, iso2: "RS", name: "Serbia", callingCode: "381" },
  { id: 29, iso2: "TL", name: "East Timor", callingCode: "670" },
  { id: 30, iso2: "RE", name: "Reunion", callingCode: "262" },
  { id: 31, iso2: "TM", name: "Turkmenistan", callingCode: "993" },
  { id: 32, iso2: "TJ", name: "Tajikistan", callingCode: "992" },
  { id: 33, iso2: "RO", name: "Romania", callingCode: "40" },
  { id: 34, iso2: "TK", name: "Tokelau", callingCode: "690" },
  { id: 35, iso2: "GW", name: "Guinea-Bissau", callingCode: "245" },
  { id: 36, iso2: "GU", name: "Guam", callingCode: "+1-671" },
  { id: 37, iso2: "GT", name: "Guatemala", callingCode: "502" },
  {
    id: 38,
    iso2: "GS",
    name: "South Georgia and the South Sandwich Islands",
    callingCode: "",
  },
  { id: 39, iso2: "GR", name: "Greece", callingCode: "30" },
  { id: 40, iso2: "GQ", name: "Equatorial Guinea", callingCode: "240" },
  { id: 41, iso2: "GP", name: "Guadeloupe", callingCode: "590" },
  { id: 42, iso2: "JP", name: "Japan", callingCode: "81" },
  { id: 43, iso2: "GY", name: "Guyana", callingCode: "592" },
  { id: 44, iso2: "GG", name: "Guernsey", callingCode: "+44-1481" },
  { id: 45, iso2: "GF", name: "French Guiana", callingCode: "594" },
  { id: 46, iso2: "GE", name: "Georgia", callingCode: "995" },
  { id: 47, iso2: "GD", name: "Grenada", callingCode: "+1-473" },
  { id: 48, iso2: "GB", name: "United Kingdom", callingCode: "44" },
  { id: 49, iso2: "GA", name: "Gabon", callingCode: "241" },
  { id: 50, iso2: "SV", name: "El Salvador", callingCode: "503" },
  { id: 51, iso2: "GN", name: "Guinea", callingCode: "224" },
  { id: 52, iso2: "GM", name: "Gambia", callingCode: "220" },
  { id: 53, iso2: "GL", name: "Greenland", callingCode: "299" },
  { id: 54, iso2: "GI", name: "Gibraltar", callingCode: "350" },
  { id: 55, iso2: "GH", name: "Ghana", callingCode: "233" },
  { id: 56, iso2: "OM", name: "Oman", callingCode: "968" },
  { id: 57, iso2: "TN", name: "Tunisia", callingCode: "216" },
  { id: 58, iso2: "JO", name: "Jordan", callingCode: "962" },
  { id: 59, iso2: "HR", name: "Croatia", callingCode: "385" },
  { id: 60, iso2: "HT", name: "Haiti", callingCode: "509" },
  { id: 61, iso2: "HU", name: "Hungary", callingCode: "36" },
  { id: 62, iso2: "HK", name: "Hong Kong", callingCode: "852" },
  { id: 63, iso2: "HN", name: "Honduras", callingCode: "504" },
  {
    id: 64,
    iso2: "HM",
    name: "Heard Island and McDonald Islands",
    callingCode: " ",
  },
  { id: 65, iso2: "VE", name: "Venezuela", callingCode: "58" },
  { id: 66, iso2: "PR", name: "Puerto Rico", callingCode: "+1-787 and 1-939" },
  { id: 67, iso2: "PS", name: "Palestinian Territory", callingCode: "970" },
  { id: 68, iso2: "PW", name: "Palau", callingCode: "680" },
  { id: 69, iso2: "PT", name: "Portugal", callingCode: "351" },
  { id: 70, iso2: "SJ", name: "Svalbard and Jan Mayen", callingCode: "47" },
  { id: 71, iso2: "PY", name: "Paraguay", callingCode: "595" },
  { id: 72, iso2: "IQ", name: "Iraq", callingCode: "964" },
  { id: 73, iso2: "PA", name: "Panama", callingCode: "507" },
  { id: 74, iso2: "PF", name: "French Polynesia", callingCode: "689" },
  { id: 75, iso2: "PG", name: "Papua New Guinea", callingCode: "675" },
  { id: 76, iso2: "PE", name: "Peru", callingCode: "51" },
  { id: 77, iso2: "PK", name: "Pakistan", callingCode: "92" },
  { id: 78, iso2: "PH", name: "Philippines", callingCode: "63" },
  { id: 79, iso2: "PN", name: "Pitcairn", callingCode: "870" },
  { id: 80, iso2: "PL", name: "Poland", callingCode: "48" },
  { id: 81, iso2: "PM", name: "Saint Pierre and Miquelon", callingCode: "508" },
  { id: 82, iso2: "ZM", name: "Zambia", callingCode: "260" },
  { id: 83, iso2: "EH", name: "Western Sahara", callingCode: "212" },
  { id: 84, iso2: "EE", name: "Estonia", callingCode: "372" },
  { id: 85, iso2: "EG", name: "Egypt", callingCode: "20" },
  { id: 86, iso2: "ZA", name: "South Africa", callingCode: "27" },
  { id: 87, iso2: "EC", name: "Ecuador", callingCode: "593" },
  { id: 88, iso2: "IT", name: "Italy", callingCode: "39" },
  { id: 89, iso2: "VN", name: "Vietnam", callingCode: "84" },
  { id: 90, iso2: "SB", name: "Solomon Islands", callingCode: "677" },
  { id: 91, iso2: "ET", name: "Ethiopia", callingCode: "251" },
  { id: 92, iso2: "SO", name: "Somalia", callingCode: "252" },
  { id: 93, iso2: "ZW", name: "Zimbabwe", callingCode: "263" },
  { id: 94, iso2: "SA", name: "Saudi Arabia", callingCode: "966" },
  { id: 95, iso2: "ES", name: "Spain", callingCode: "34" },
  { id: 96, iso2: "ER", name: "Eritrea", callingCode: "291" },
  { id: 97, iso2: "ME", name: "Montenegro", callingCode: "382" },
  { id: 98, iso2: "MD", name: "Moldova", callingCode: "373" },
  { id: 99, iso2: "MG", name: "Madagascar", callingCode: "261" },
  { id: 100, iso2: "MF", name: "Saint Martin", callingCode: "590" },
  { id: 101, iso2: "MA", name: "Morocco", callingCode: "212" },
  { id: 102, iso2: "MC", name: "Monaco", callingCode: "377" },
  { id: 103, iso2: "UZ", name: "Uzbekistan", callingCode: "998" },
  { id: 104, iso2: "MM", name: "Myanmar", callingCode: "95" },
  { id: 105, iso2: "ML", name: "Mali", callingCode: "223" },
  { id: 106, iso2: "MO", name: "Macao", callingCode: "853" },
  { id: 107, iso2: "MN", name: "Mongolia", callingCode: "976" },
  { id: 108, iso2: "MH", name: "Marshall Islands", callingCode: "692" },
  { id: 109, iso2: "MK", name: "Macedonia", callingCode: "389" },
  { id: 110, iso2: "MU", name: "Mauritius", callingCode: "230" },
  { id: 111, iso2: "MT", name: "Malta", callingCode: "356" },
  { id: 112, iso2: "MW", name: "Malawi", callingCode: "265" },
  { id: 113, iso2: "MV", name: "Maldives", callingCode: "960" },
  { id: 114, iso2: "MQ", name: "Martinique", callingCode: "596" },
  {
    id: 115,
    iso2: "MP",
    name: "Northern Mariana Islands",
    callingCode: "+1-670",
  },
  { id: 116, iso2: "MS", name: "Montserrat", callingCode: "+1-664" },
  { id: 117, iso2: "MR", name: "Mauritania", callingCode: "222" },
  { id: 118, iso2: "IM", name: "Isle of Man", callingCode: "+44-1624" },
  { id: 119, iso2: "UG", name: "Uganda", callingCode: "256" },
  { id: 120, iso2: "TZ", name: "Tanzania", callingCode: "255" },
  { id: 121, iso2: "MY", name: "Malaysia", callingCode: "60" },
  { id: 122, iso2: "MX", name: "Mexico", callingCode: "52" },
  { id: 123, iso2: "IL", name: "Israel", callingCode: "972" },
  { id: 124, iso2: "FR", name: "France", callingCode: "33" },
  {
    id: 125,
    iso2: "IO",
    name: "British Indian Ocean Territory",
    callingCode: "246",
  },
  { id: 126, iso2: "SH", name: "Saint Helena", callingCode: "290" },
  { id: 127, iso2: "FI", name: "Finland", callingCode: "358" },
  { id: 128, iso2: "FJ", name: "Fiji", callingCode: "679" },
  { id: 129, iso2: "FK", name: "Falkland Islands", callingCode: "500" },
  { id: 130, iso2: "FM", name: "Micronesia", callingCode: "691" },
  { id: 131, iso2: "FO", name: "Faroe Islands", callingCode: "298" },
  { id: 132, iso2: "NI", name: "Nicaragua", callingCode: "505" },
  { id: 133, iso2: "NL", name: "Netherlands", callingCode: "31" },
  { id: 134, iso2: "NO", name: "Norway", callingCode: "47" },
  { id: 135, iso2: "NA", name: "Namibia", callingCode: "264" },
  { id: 136, iso2: "VU", name: "Vanuatu", callingCode: "678" },
  { id: 137, iso2: "NC", name: "New Caledonia", callingCode: "687" },
  { id: 138, iso2: "NE", name: "Niger", callingCode: "227" },
  { id: 139, iso2: "NF", name: "Norfolk Island", callingCode: "672" },
  { id: 140, iso2: "NG", name: "Nigeria", callingCode: "234" },
  { id: 141, iso2: "NZ", name: "New Zealand", callingCode: "64" },
  { id: 142, iso2: "NP", name: "Nepal", callingCode: "977" },
  { id: 143, iso2: "NR", name: "Nauru", callingCode: "674" },
  { id: 144, iso2: "NU", name: "Niue", callingCode: "683" },
  { id: 145, iso2: "CK", name: "Cook Islands", callingCode: "682" },
  { id: 146, iso2: "XK", name: "Kosovo", callingCode: "" },
  { id: 147, iso2: "CI", name: "Ivory Coast", callingCode: "225" },
  { id: 148, iso2: "CH", name: "Switzerland", callingCode: "41" },
  { id: 149, iso2: "CO", name: "Colombia", callingCode: "57" },
  { id: 150, iso2: "CN", name: "China", callingCode: "86" },
  { id: 151, iso2: "CM", name: "Cameroon", callingCode: "237" },
  { id: 152, iso2: "CL", name: "Chile", callingCode: "56" },
  { id: 153, iso2: "CC", name: "Cocos Islands", callingCode: "61" },
  { id: 154, iso2: "CA", name: "Canada", callingCode: "1" },
  { id: 155, iso2: "CG", name: "Republic of the Congo", callingCode: "242" },
  { id: 156, iso2: "CF", name: "Central African Republic", callingCode: "236" },
  {
    id: 157,
    iso2: "CD",
    name: "Democratic Republic of the Congo",
    callingCode: "243",
  },
  { id: 158, iso2: "CZ", name: "Czech Republic", callingCode: "420" },
  { id: 159, iso2: "CY", name: "Cyprus", callingCode: "357" },
  { id: 160, iso2: "CX", name: "Christmas Island", callingCode: "61" },
  { id: 161, iso2: "CR", name: "Costa Rica", callingCode: "506" },
  { id: 162, iso2: "CW", name: "Curacao", callingCode: "599" },
  { id: 163, iso2: "CV", name: "Cape Verde", callingCode: "238" },
  { id: 164, iso2: "CU", name: "Cuba", callingCode: "53" },
  { id: 165, iso2: "SZ", name: "Swaziland", callingCode: "268" },
  { id: 166, iso2: "SY", name: "Syria", callingCode: "963" },
  { id: 167, iso2: "SX", name: "Sint Maarten", callingCode: "599" },
  { id: 168, iso2: "KG", name: "Kyrgyzstan", callingCode: "996" },
  { id: 169, iso2: "KE", name: "Kenya", callingCode: "254" },
  { id: 170, iso2: "SS", name: "South Sudan", callingCode: "211" },
  { id: 171, iso2: "SR", name: "Suriname", callingCode: "597" },
  { id: 172, iso2: "KI", name: "Kiribati", callingCode: "686" },
  { id: 173, iso2: "KH", name: "Cambodia", callingCode: "855" },
  { id: 174, iso2: "KN", name: "Saint Kitts and Nevis", callingCode: "+1-869" },
  { id: 175, iso2: "KM", name: "Comoros", callingCode: "269" },
  { id: 176, iso2: "ST", name: "Sao Tome and Principe", callingCode: "239" },
  { id: 177, iso2: "SK", name: "Slovakia", callingCode: "421" },
  { id: 178, iso2: "KR", name: "South Korea", callingCode: "82" },
  { id: 179, iso2: "SI", name: "Slovenia", callingCode: "386" },
  { id: 180, iso2: "KP", name: "North Korea", callingCode: "850" },
  { id: 181, iso2: "KW", name: "Kuwait", callingCode: "965" },
  { id: 182, iso2: "SN", name: "Senegal", callingCode: "221" },
  { id: 183, iso2: "SM", name: "San Marino", callingCode: "378" },
  { id: 184, iso2: "SL", name: "Sierra Leone", callingCode: "232" },
  { id: 185, iso2: "SC", name: "Seychelles", callingCode: "248" },
  { id: 186, iso2: "KZ", name: "Kazakhstan", callingCode: "7" },
  { id: 187, iso2: "KY", name: "Cayman Islands", callingCode: "+1-345" },
  { id: 188, iso2: "SG", name: "Singapore", callingCode: "65" },
  { id: 189, iso2: "SE", name: "Sweden", callingCode: "46" },
  { id: 190, iso2: "SD", name: "Sudan", callingCode: "249" },
  {
    id: 191,
    iso2: "DO",
    name: "Dominican Republic",
    callingCode: "+1-809 and 1-829",
  },
  { id: 192, iso2: "DM", name: "Dominica", callingCode: "+1-767" },
  { id: 193, iso2: "DJ", name: "Djibouti", callingCode: "253" },
  { id: 194, iso2: "DK", name: "Denmark", callingCode: "45" },
  {
    id: 195,
    iso2: "VG",
    name: "British Virgin Islands",
    callingCode: "+1-284",
  },
  { id: 196, iso2: "DE", name: "Germany", callingCode: "49" },
  { id: 197, iso2: "YE", name: "Yemen", callingCode: "967" },
  { id: 198, iso2: "DZ", name: "Algeria", callingCode: "213" },
  { id: 199, iso2: "US", name: "United States", callingCode: "1" },
  { id: 200, iso2: "UY", name: "Uruguay", callingCode: "598" },
  { id: 201, iso2: "YT", name: "Mayotte", callingCode: "262" },
  {
    id: 202,
    iso2: "UM",
    name: "United States Minor Outlying Islands",
    callingCode: "1",
  },
  { id: 203, iso2: "LB", name: "Lebanon", callingCode: "961" },
  { id: 204, iso2: "LC", name: "Saint Lucia", callingCode: "+1-758" },
  { id: 205, iso2: "LA", name: "Laos", callingCode: "856" },
  { id: 206, iso2: "TV", name: "Tuvalu", callingCode: "688" },
  { id: 207, iso2: "TW", name: "Taiwan", callingCode: "886" },
  { id: 208, iso2: "TT", name: "Trinidad and Tobago", callingCode: "+1-868" },
  { id: 209, iso2: "TR", name: "Turkey", callingCode: "90" },
  { id: 210, iso2: "LK", name: "Sri Lanka", callingCode: "94" },
  { id: 211, iso2: "LI", name: "Liechtenstein", callingCode: "423" },
  { id: 212, iso2: "LV", name: "Latvia", callingCode: "371" },
  { id: 213, iso2: "TO", name: "Tonga", callingCode: "676" },
  { id: 214, iso2: "LT", name: "Lithuania", callingCode: "370" },
  { id: 215, iso2: "LU", name: "Luxembourg", callingCode: "352" },
  { id: 216, iso2: "LR", name: "Liberia", callingCode: "231" },
  { id: 217, iso2: "LS", name: "Lesotho", callingCode: "266" },
  { id: 218, iso2: "TH", name: "Thailand", callingCode: "66" },
  { id: 219, iso2: "TF", name: "French Southern Territories", callingCode: "" },
  { id: 220, iso2: "TG", name: "Togo", callingCode: "228" },
  { id: 221, iso2: "TD", name: "Chad", callingCode: "235" },
  {
    id: 222,
    iso2: "TC",
    name: "Turks and Caicos Islands",
    callingCode: "+1-649",
  },
  { id: 223, iso2: "LY", name: "Libya", callingCode: "218" },
  { id: 224, iso2: "VA", name: "Vatican", callingCode: "379" },
  {
    id: 225,
    iso2: "VC",
    name: "Saint Vincent and the Grenadines",
    callingCode: "+1-784",
  },
  { id: 226, iso2: "AE", name: "United Arab Emirates", callingCode: "971" },
  { id: 227, iso2: "AD", name: "Andorra", callingCode: "376" },
  { id: 228, iso2: "AG", name: "Antigua and Barbuda", callingCode: "+1-268" },
  { id: 229, iso2: "AF", name: "Afghanistan", callingCode: "93" },
  { id: 230, iso2: "AI", name: "Anguilla", callingCode: "+1-264" },
  { id: 231, iso2: "VI", name: "U.S. Virgin Islands", callingCode: "+1-340" },
  { id: 232, iso2: "IS", name: "Iceland", callingCode: "354" },
  { id: 233, iso2: "IR", name: "Iran", callingCode: "98" },
  { id: 234, iso2: "AM", name: "Armenia", callingCode: "374" },
  { id: 235, iso2: "AL", name: "Albania", callingCode: "355" },
  { id: 236, iso2: "AO", name: "Angola", callingCode: "244" },
  { id: 237, iso2: "AQ", name: "Antarctica", callingCode: "" },
  { id: 238, iso2: "AS", name: "American Samoa", callingCode: "+1-684" },
  { id: 239, iso2: "AR", name: "Argentina", callingCode: "54" },
  { id: 240, iso2: "AU", name: "Australia", callingCode: "61" },
  { id: 241, iso2: "AT", name: "Austria", callingCode: "43" },
  { id: 242, iso2: "AW", name: "Aruba", callingCode: "297" },
  { id: 243, iso2: "IN", name: "India", callingCode: "91" },
  { id: 244, iso2: "AX", name: "Aland Islands", callingCode: "+358-18" },
  { id: 245, iso2: "AZ", name: "Azerbaijan", callingCode: "994" },
  { id: 246, iso2: "IE", name: "Ireland", callingCode: "353" },
  { id: 247, iso2: "ID", name: "Indonesia", callingCode: "62" },
  { id: 248, iso2: "UA", name: "Ukraine", callingCode: "380" },
  { id: 249, iso2: "QA", name: "Qatar", callingCode: "974" },
  { id: 250, iso2: "MZ", name: "Mozambique", callingCode: "258" },
];
